import wasmDataUrl from "sourmash/sourmash_bg.wasm";
import * as sourmashBindings from "sourmash/sourmash_bg.js";

// sourmash was compiled expecting a set of native compression helpers
// (zstd/lzma) to be supplied by the host environment. They are not
// available in the browser build, so we provide stubs that surface a
// clear error if they are ever invoked.
const missingCompressionFn = (name: string) => () => {
  throw new Error(`${name} is not available in the browser build of sourmash`);
};

const envImports = {
  lzma_code: missingCompressionFn("lzma_code"),
  ZSTD_decompressStream: missingCompressionFn("ZSTD_decompressStream"),
  lzma_end: missingCompressionFn("lzma_end"),
  lzma_stream_decoder: missingCompressionFn("lzma_stream_decoder"),
  ZSTD_isError: missingCompressionFn("ZSTD_isError"),
  ZSTD_getErrorName: missingCompressionFn("ZSTD_getErrorName"),
  ZSTD_createDCtx: missingCompressionFn("ZSTD_createDCtx"),
  ZSTD_initDStream: missingCompressionFn("ZSTD_initDStream"),
  ZSTD_DCtx_reset: missingCompressionFn("ZSTD_DCtx_reset"),
  ZSTD_DCtx_loadDictionary: missingCompressionFn("ZSTD_DCtx_loadDictionary"),
  ZSTD_DStreamInSize: missingCompressionFn("ZSTD_DStreamInSize"),
  ZSTD_freeDCtx: missingCompressionFn("ZSTD_freeDCtx"),
};

let sourmashReady: Promise<typeof sourmashBindings> | null = null;

function dataUrlToUint8Array(dataUrl: string): Uint8Array {
  const [, base64] = dataUrl.split(",");
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

export async function loadSourmash() {
  if (!sourmashReady) {
    sourmashReady = (async () => {
      const bytes = dataUrlToUint8Array(wasmDataUrl);

      const importObject: WebAssembly.Imports = {
        "./sourmash_bg.js": sourmashBindings as unknown as WebAssembly.ModuleImports,
        env: envImports,
      };

      const { instance } = await WebAssembly.instantiate(bytes, importObject);

      // Wire up the wasm exports with the JS glue code generated by wasm-bindgen.
      (sourmashBindings as any).__wbg_set_wasm(instance.exports);
      const start = (instance.exports as any).__wbindgen_start;
      if (typeof start === "function") {
        start();
      }

      return sourmashBindings;
    })();
  }

  return sourmashReady;
}

export default loadSourmash;
